### ISSUE TITLE
Key assumed to be in a cookie fails on login->logout->login.

### ISSUE THREAD

**Issue by bbuechler** [asfadmin/thin-egress-app#106]
```
Traceback (most recent call last):
  File "/opt/python/chalice/app.py", line 1104, in _get_view_function_response
    response = view_function(**function_args)
  File "/var/task/app.py", line 212, in logout
    user_id = cookievars['urs-user-id']
KeyError: 'urs-user-id'
```

https://github.com/asfadmin/thin-egress-app/blob/5e8920aec9f16314a39f58e25cdcce9da877ae78/lambda/app.py#L212

This value should be wrapped in a `if 'urs-user-id' in cookievars:` block.

**Comment by bbuechler** [comment]
Resolved in https://github.com/asfadmin/thin-egress-app/pull/119
